"""Socket-free AppManager-to-mouth-LED integration diagnostic."""

import collections
import json
import struct
import sys

from robot_controller.hardware.vsmd.app_manager_codec import (
    JAVA_SHORT_SERIALIZATION_PREFIX,
    SERIALIZED_OK,
)
from robot_controller.hardware.vsmd.app_manager_lock import AppManagerLedLock
from robot_controller.hardware.vsmd.app_manager_vsmd_lock import (
    AppManagerLeaseInterpolationTimer,
    AppManagerVsmdLedLock,
)
from robot_controller.hardware.vsmd.memory import VsmdMemoryAccess
from robot_controller.hardware.vsmd.mouth_led import SotaMouthLedController
from robot_controller.hardware.vsmd.sota_memory_map import (
    MOUTH_LED_SELECTOR_ADDRESS,
    SOTA_MOUTH_GLOBAL_LED_ID,
    SOTA_MOUTH_TARGET_ADDRESS,
)
from robot_controller.hardware.vsmd.typed_memory import VsmdTypedMemory


DRY_RUN_TIMER_ADDRESS = 502
DRY_RUN_BRIGHTNESS = 16
DRY_RUN_DURATION_MS = 200


_DryRunResultBase = collections.namedtuple(
    "_DryRunResultBase",
    ["timer_address", "operations", "events"],
)


class DryRunResult(_DryRunResultBase):
    """Immutable record generated entirely by Fake transports."""

    __slots__ = ()


class _DryRunAppManagerTransport(object):
    def __init__(self, events):
        self._events = events

    def request(self, request_json):
        outer = json.loads(request_json.decode("ascii"))
        command = outer["cmd"]
        self._events.append(command)
        if command == "INTERP_CNV_KEY_2_ADDR":
            return JAVA_SHORT_SERIALIZATION_PREFIX + struct.pack(
                ">h", DRY_RUN_TIMER_ADDRESS
            )
        return SERIALIZED_OK


class _DryRunVsmdMemory(VsmdMemoryAccess):
    def __init__(self, events):
        self._events = events
        self._data = bytearray(b"\x00" * 65536)
        self._data[
            MOUTH_LED_SELECTOR_ADDRESS:MOUTH_LED_SELECTOR_ADDRESS + 2
        ] = struct.pack("<H", 138)
        self._data[
            SOTA_MOUTH_TARGET_ADDRESS:SOTA_MOUTH_TARGET_ADDRESS + 2
        ] = struct.pack("<h", 0)
        self.operations = []

    def read_bytes(self, address, size):
        operation = ("read_bytes", address, size)
        self.operations.append(operation)
        self._events.append(operation)
        return bytes(self._data[address:address + size])

    def write_bytes(self, address, payload):
        payload = bytes(payload)
        operation = ("write_bytes", address, payload)
        self.operations.append(operation)
        self._events.append(operation)
        self._data[address:address + len(payload)] = payload


def execute_dry_run():
    # type: () -> DryRunResult
    """Exercise the real controller and adapters using Fake ports only."""
    events = []
    app_manager_transport = _DryRunAppManagerTransport(events)
    app_manager_lock = AppManagerLedLock(
        transport=app_manager_transport,
        key_factory=lambda: "dry-run-key",
    )
    adapter = AppManagerVsmdLedLock(app_manager_lock)
    raw_memory = _DryRunVsmdMemory(events)
    memory = VsmdTypedMemory(raw_memory)
    timer = AppManagerLeaseInterpolationTimer(memory, adapter)
    controller = SotaMouthLedController(
        memory,
        timer,
        led_lock=adapter,
        lock_key="dry-run-mouth",
    )

    controller.disable_voice_sync()
    timer_address = adapter.timer_address_for(SOTA_MOUTH_GLOBAL_LED_ID)
    try:
        controller.set_brightness(
            DRY_RUN_BRIGHTNESS, DRY_RUN_DURATION_MS
        )
    finally:
        controller.close()
    return DryRunResult(
        timer_address,
        tuple(raw_memory.operations),
        tuple(events),
    )


def _format_operation(operation):
    if operation[0] == "read_bytes":
        return "read_bytes(address=0x{0:04x},size={1})".format(
            operation[1], operation[2]
        )
    return "write_bytes(address=0x{0:04x},payload={1})".format(
        operation[1], operation[2].hex()
    )


def main():
    # type: () -> int
    """Print the actual Fake operations generated by the existing controller."""
    print("Sota AppManager mouth LED dry-run")
    print("led_id={0}".format(SOTA_MOUTH_GLOBAL_LED_ID))
    print("live_network=false")
    print("live_write=false")
    try:
        result = execute_dry_run()
    except BaseException as error:
        print("result=failure")
        print("error_type={0}".format(type(error).__name__))
        print("error={0}".format(error))
        return 1

    print("lock_acquired=true")
    print("timer_address={0}".format(result.timer_address))
    print(
        "processing_order=LOCK>CONVERT>validate timer address>"
        "prepare VSMD LED operations>perform Fake VSMD operations>UNLOCK"
    )
    print(
        "planned_vsmd_operations={0}".format(
            ";".join(
                _format_operation(operation)
                for operation in result.operations
            )
        )
    )
    print("lock_released=true")
    print("result=success")
    return 0


if __name__ == "__main__":
    sys.exit(main())
