"""Connection defaults and bounded protocol constants for ``vsmd_edison``."""

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 6498
DEFAULT_CONNECT_TIMEOUT_SECONDS = 1.0
DEFAULT_READ_TIMEOUT_SECONDS = 1.0
DEFAULT_WRITE_TIMEOUT_SECONDS = 1.0
DEFAULT_MAX_LINE_LENGTH = 4096
MIN_ADDRESS = 0
MAX_ADDRESS = 0xFFFF

